[package]
name = "ebclup"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
clap_complete = "4.5.46"
flate2 = "1.1.0"
tar = "0.4.44"

[build-dependencies]
